spring:
  application:
    name: industrial-iot-backend
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:industrial_iiot_db}
    username: ${POSTGRES_USER:iiot_user}
    password: ${POSTGRES_PASSWORD:135790}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

mqtt:
  broker:
    url: tcp://${MQTT_BROKER_HOST:localhost}:${MQTT_BROKER_PORT:1883}
  client:
    id: ${MQTT_CLIENT_ID:industrial-backend-consumer}
  topic:
    telemetry: ${MQTT_TELEMETRY_TOPIC:industry/machinery/+}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false