package henrique.igor.iiot.application.usecases.actuator;

import henrique.igor.iiot.application.usecases.actuator.dto.RegisterActuatorInput;
import henrique.igor.iiot.domain.entities.Actuator;
import henrique.igor.iiot.domain.entities.Equipment;
import henrique.igor.iiot.domain.entities.enums.ActuatorType;
import henrique.igor.iiot.domain.entities.enums.EquipStatus;
import henrique.igor.iiot.domain.entities.enums.EquipType;
import henrique.igor.iiot.domain.repositories.ActuatorRepository;
import henrique.igor.iiot.domain.repositories.EquipmentRepository;
import henrique.igor.iiot.domain.services.ActuatorCodeGenerator;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RegisterActuatorUseCaseTest {

    @Mock
    private ActuatorRepository actuatorRepository;

    @Mock
    private EquipmentRepository equipmentRepository;

    @Mock
    private ActuatorCodeGenerator actuatorCodeGenerator;

    @InjectMocks
    private RegisterActuatorUseCase registerActuatorUseCase;

    @Test
    @DisplayName("Should register actuator with auto-generated code when equipment is provided")
    void shouldRegisterActuatorWithAutoGeneratedCodeWhenEquipmentProvided() {
        UUID equipmentId = UUID.randomUUID();
        Equipment equipment = new Equipment(equipmentId, "MTR-USI-001", EquipType.MOTOR, EquipStatus.ACTIVE, null, null, OffsetDateTime.now());

        RegisterActuatorInput input = new RegisterActuatorInput(
                null,
                ActuatorType.RELAY,
                "cmd/relay/1",
                "state/relay/1",
                equipmentId
        );

        when(equipmentRepository.findById(equipmentId)).thenReturn(Optional.of(equipment));
        when(actuatorCodeGenerator.generate(ActuatorType.RELAY, equipment)).thenReturn("RLY-001-MTR-USI-001");
        when(actuatorRepository.save(any(Actuator.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Actuator result = registerActuatorUseCase.execute(input);

        assertNotNull(result);
        assertEquals("RLY-001-MTR-USI-001", result.getCode());
        assertEquals(ActuatorType.RELAY, result.getActuatorType());
        assertEquals("cmd/relay/1", result.getCommandMqttTopic());
        assertEquals("state/relay/1", result.getStateMqttTopic());
        assertEquals(equipment, result.getEquipment());

        verify(actuatorCodeGenerator, times(1)).generate(ActuatorType.RELAY, equipment);
        verify(actuatorRepository, times(1)).save(any(Actuator.class));
    }

    @Test
    @DisplayName("Should register actuator with provided code")
    void shouldRegisterActuatorWithProvidedCode() {
        RegisterActuatorInput input = new RegisterActuatorInput(
                "CUSTOM-ACT-01",
                ActuatorType.VALVE,
                "cmd/valve",
                "state/valve",
                null
        );

        when(actuatorRepository.findByCode("CUSTOM-ACT-01")).thenReturn(Optional.empty());
        when(actuatorRepository.save(any(Actuator.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Actuator result = registerActuatorUseCase.execute(input);

        assertNotNull(result);
        assertEquals("CUSTOM-ACT-01", result.getCode());
        assertEquals(ActuatorType.VALVE, result.getActuatorType());

        verify(actuatorRepository, times(1)).save(any(Actuator.class));
    }

    @Test
    @DisplayName("Should throw exception when actuator type is null")
    void shouldThrowExceptionWhenTypeIsNull() {
        RegisterActuatorInput input = new RegisterActuatorInput(
                "ACT-01",
                null,
                "cmd",
                "state",
                null
        );

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerActuatorUseCase.execute(input));

        assertEquals("Actuator type cannot be null.", exception.getMessage());
        verify(actuatorRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw exception when equipment is not found")
    void shouldThrowExceptionWhenEquipmentNotFound() {
        UUID equipmentId = UUID.randomUUID();
        RegisterActuatorInput input = new RegisterActuatorInput(
                null,
                ActuatorType.VALVE,
                "cmd",
                "state",
                equipmentId
        );

        when(equipmentRepository.findById(equipmentId)).thenReturn(Optional.empty());

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerActuatorUseCase.execute(input));

        assertEquals("Equipment not found with ID: " + equipmentId, exception.getMessage());
        verify(actuatorRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw exception when actuator code already exists")
    void shouldThrowExceptionWhenCodeAlreadyExists() {
        RegisterActuatorInput input = new RegisterActuatorInput(
                "EXISTING-ACT",
                ActuatorType.MOTOR,
                "cmd",
                "state",
                null
        );

        Actuator existing = new Actuator("EXISTING-ACT", ActuatorType.MOTOR, "cmd", "state", null);
        when(actuatorRepository.findByCode("EXISTING-ACT")).thenReturn(Optional.of(existing));

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerActuatorUseCase.execute(input));

        assertEquals("Actuator with code EXISTING-ACT already exists.", exception.getMessage());
        verify(actuatorRepository, never()).save(any());
    }
}