package henrique.igor.iiot.application.usecases.sensor;

import henrique.igor.iiot.application.usecases.sensor.dto.RegisterSensorRequest;
import henrique.igor.iiot.domain.entities.Equipment;
import henrique.igor.iiot.domain.entities.Sensor;
import henrique.igor.iiot.domain.entities.enums.EquipType;
import henrique.igor.iiot.domain.entities.enums.SensorStatus;
import henrique.igor.iiot.domain.entities.enums.SensorType;
import henrique.igor.iiot.domain.repositories.EquipmentRepository;
import henrique.igor.iiot.domain.repositories.SensorRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import henrique.igor.iiot.domain.services.SensorCodeGenerator;

class RegisterSensorUseCaseTest {

    private SensorRepository sensorRepository;
    private EquipmentRepository equipmentRepository;
    private SensorCodeGenerator sensorCodeGenerator;
    private RegisterSensorUseCase registerSensorUseCase;

    @BeforeEach
    void setUp() {
        sensorRepository = mock(SensorRepository.class);
        equipmentRepository = mock(EquipmentRepository.class);
        sensorCodeGenerator = new SensorCodeGenerator(sensorRepository);
        registerSensorUseCase = new RegisterSensorUseCase(sensorRepository, equipmentRepository, sensorCodeGenerator);
    }

    @Test
    @DisplayName("Should register sensor with auto-generated code linked to equipment")
    void shouldRegisterSensorWithAutoGeneratedCodeWhenEquipmentProvided() {
        UUID equipmentId = UUID.randomUUID();
        Equipment equipment = new Equipment(equipmentId, "MTR-USI-001", EquipType.MOTOR, henrique.igor.iiot.domain.entities.enums.EquipStatus.ACTIVE, null, null, java.time.OffsetDateTime.now());

        RegisterSensorRequest request = new RegisterSensorRequest(
                null,
                SensorType.TEMPERATURE,
                SensorStatus.ONLINE,
                "°C",
                "telemetry/tem/001",
                equipmentId
        );

        when(equipmentRepository.findById(equipmentId)).thenReturn(Optional.of(equipment));
        when(sensorRepository.countByEquipmentIdAndSensorType(equipmentId, SensorType.TEMPERATURE)).thenReturn(0L);
        when(sensorRepository.save(any(Sensor.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Sensor result = registerSensorUseCase.execute(request);

        assertNotNull(result);
        assertEquals("TEM-001-MTR-USI-001", result.getCode());
        assertEquals(SensorType.TEMPERATURE, result.getSensorType());
        assertEquals("°C", result.getUnitOfMeasure());
        assertEquals(equipment, result.getEquipment());

        verify(sensorRepository, times(1)).save(any(Sensor.class));
    }

    @Test
    @DisplayName("Should register sensor with auto-generated code when no equipment provided")
    void shouldRegisterSensorWithAutoGeneratedCodeWhenNoEquipmentProvided() {
        RegisterSensorRequest request = new RegisterSensorRequest(
                "",
                SensorType.VIBRATION,
                SensorStatus.ONLINE,
                "mm/s",
                "telemetry/vib/gen",
                null
        );

        when(sensorRepository.countByEquipmentIdIsNullAndSensorType(SensorType.VIBRATION)).thenReturn(1L);
        when(sensorRepository.save(any(Sensor.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Sensor result = registerSensorUseCase.execute(request);

        assertNotNull(result);
        assertEquals("VIB-002-GEN", result.getCode());
        assertNull(result.getEquipment());
    }

    @Test
    @DisplayName("Should register sensor with custom provided code")
    void shouldRegisterSensorWithProvidedCode() {
        RegisterSensorRequest request = new RegisterSensorRequest(
                "CUSTOM-SEN-99",
                SensorType.CURRENT,
                SensorStatus.ONLINE,
                "A",
                "telemetry/cur/custom",
                null
        );

        when(sensorRepository.findByCode("CUSTOM-SEN-99")).thenReturn(Optional.empty());
        when(sensorRepository.save(any(Sensor.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Sensor result = registerSensorUseCase.execute(request);

        assertNotNull(result);
        assertEquals("CUSTOM-SEN-99", result.getCode());
    }

    @Test
    @DisplayName("Should throw exception when sensor type is null")
    void shouldThrowExceptionWhenSensorTypeIsNull() {
        RegisterSensorRequest request = new RegisterSensorRequest(
                null,
                null,
                SensorStatus.ONLINE,
                "A",
                "topic",
                null
        );

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerSensorUseCase.execute(request));

        assertEquals("Sensor type cannot be null.", exception.getMessage());
    }

    @Test
    @DisplayName("Should throw exception when equipment is not found")
    void shouldThrowExceptionWhenEquipmentNotFound() {
        UUID equipmentId = UUID.randomUUID();
        RegisterSensorRequest request = new RegisterSensorRequest(
                null,
                SensorType.PRESSURE,
                SensorStatus.ONLINE,
                "bar",
                "topic",
                equipmentId
        );

        when(equipmentRepository.findById(equipmentId)).thenReturn(Optional.empty());

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerSensorUseCase.execute(request));

        assertEquals("Equipment not found with ID: " + equipmentId, exception.getMessage());
    }

    @Test
    @DisplayName("Should throw exception when code already exists")
    void shouldThrowExceptionWhenCodeAlreadyExists() {
        RegisterSensorRequest request = new RegisterSensorRequest(
                "EXISTING-CODE",
                SensorType.VOLTAGE,
                SensorStatus.ONLINE,
                "V",
                "topic",
                null
        );

        Sensor existingSensor = new Sensor("EXISTING-CODE", SensorType.VOLTAGE, "V", "topic", null);
        when(sensorRepository.findByCode("EXISTING-CODE")).thenReturn(Optional.of(existingSensor));

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerSensorUseCase.execute(request));

        assertEquals("Sensor with code EXISTING-CODE already exists.", exception.getMessage());
    }
}
