package henrique.igor.iiot.application.usecases.sensor;

import henrique.igor.iiot.application.usecases.sensor.dto.RegisterSensorInput;
import henrique.igor.iiot.domain.entities.Equipment;
import henrique.igor.iiot.domain.entities.Sensor;
import henrique.igor.iiot.domain.entities.enums.EquipType;
import henrique.igor.iiot.domain.entities.enums.SensorStatus;
import henrique.igor.iiot.domain.entities.enums.SensorType;
import henrique.igor.iiot.domain.repositories.EquipmentRepository;
import henrique.igor.iiot.domain.repositories.SensorRepository;
import henrique.igor.iiot.domain.services.SensorCodeGenerator;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RegisterSensorUseCaseTest {

    @Mock
    private SensorRepository sensorRepository;

    @Mock
    private EquipmentRepository equipmentRepository;

    @Mock
    private SensorCodeGenerator sensorCodeGenerator;

    @InjectMocks
    private RegisterSensorUseCase registerSensorUseCase;

    @Test
    @DisplayName("Should register sensor with auto-generated code linked to equipment")
    void shouldRegisterSensorWithAutoGeneratedCodeWhenEquipmentProvided() {
        UUID equipmentId = UUID.randomUUID();
        Equipment equipment = new Equipment(equipmentId, "MTR-USI-001", EquipType.MOTOR, henrique.igor.iiot.domain.entities.enums.EquipStatus.ACTIVE, null, null, java.time.OffsetDateTime.now());

        RegisterSensorInput request = new RegisterSensorInput(
                null,
                SensorType.TEMPERATURE,
                "°C",
                "telemetry/tem/001",
                equipmentId
        );

        when(equipmentRepository.findById(equipmentId)).thenReturn(Optional.of(equipment));
        when(sensorCodeGenerator.generate(SensorType.TEMPERATURE, equipment)).thenReturn("TEM-001-MTR-USI-001");
        when(sensorRepository.save(any(Sensor.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Sensor result = registerSensorUseCase.execute(request);

        assertNotNull(result);
        assertEquals("TEM-001-MTR-USI-001", result.getCode());
        assertEquals(SensorType.TEMPERATURE, result.getSensorType());
        assertEquals("°C", result.getUnitOfMeasure());
        assertEquals(equipment, result.getEquipment());

        verify(sensorCodeGenerator, times(1)).generate(SensorType.TEMPERATURE, equipment);
        verify(sensorRepository, times(1)).save(any(Sensor.class));
    }

    @Test
    @DisplayName("Should register sensor with auto-generated code when no equipment provided")
    void shouldRegisterSensorWithAutoGeneratedCodeWhenNoEquipmentProvided() {
        RegisterSensorInput request = new RegisterSensorInput(
                "",
                SensorType.VIBRATION,
                "mm/s",
                "telemetry/vib/gen",
                null
        );

        when(sensorCodeGenerator.generate(SensorType.VIBRATION, null)).thenReturn("VIB-002-GEN");
        when(sensorRepository.save(any(Sensor.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Sensor result = registerSensorUseCase.execute(request);

        assertNotNull(result);
        assertEquals("VIB-002-GEN", result.getCode());
        assertNull(result.getEquipment());
        verify(sensorCodeGenerator, times(1)).generate(SensorType.VIBRATION, null);
    }

    @Test
    @DisplayName("Should register sensor with custom provided code")
    void shouldRegisterSensorWithProvidedCode() {
        RegisterSensorInput request = new RegisterSensorInput(
                "CUSTOM-SEN-99",
                SensorType.CURRENT,
                "A",
                "telemetry/cur/custom",
                null
        );

        when(sensorRepository.findByCode("CUSTOM-SEN-99")).thenReturn(Optional.empty());
        when(sensorRepository.save(any(Sensor.class))).thenAnswer(invocation -> invocation.getArgument(0));

        Sensor result = registerSensorUseCase.execute(request);

        assertNotNull(result);
        assertEquals("CUSTOM-SEN-99", result.getCode());
    }

    @Test
    @DisplayName("Should throw exception when sensor type is null")
    void shouldThrowExceptionWhenSensorTypeIsNull() {
        RegisterSensorInput request = new RegisterSensorInput(
                null,
                null,
                "A",
                "topic",
                null
        );

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerSensorUseCase.execute(request));

        assertEquals("Sensor type cannot be null.", exception.getMessage());
    }

    @Test
    @DisplayName("Should throw exception when equipment is not found")
    void shouldThrowExceptionWhenEquipmentNotFound() {
        UUID equipmentId = UUID.randomUUID();
        RegisterSensorInput request = new RegisterSensorInput(
                null,
                SensorType.PRESSURE,
                "bar",
                "topic",
                equipmentId
        );

        when(equipmentRepository.findById(equipmentId)).thenReturn(Optional.empty());

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerSensorUseCase.execute(request));

        assertEquals("Equipment not found with ID: " + equipmentId, exception.getMessage());
    }

    @Test
    @DisplayName("Should throw exception when code already exists")
    void shouldThrowExceptionWhenCodeAlreadyExists() {
        RegisterSensorInput request = new RegisterSensorInput(
                "EXISTING-CODE",
                SensorType.VOLTAGE,
                "V",
                "topic",
                null
        );

        Sensor existingSensor = new Sensor("EXISTING-CODE", SensorType.VOLTAGE, "V", "topic", null);
        when(sensorRepository.findByCode("EXISTING-CODE")).thenReturn(Optional.of(existingSensor));

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> registerSensorUseCase.execute(request));

        assertEquals("Sensor with code EXISTING-CODE already exists.", exception.getMessage());
    }
}
